<?php
session_start();

include 'connection.php';

$ord_date = date("Y-m-d");
$u_id = $_SESSION['user_id'];
$amount = $_SESSION['price'];
$i_id = $_SESSION['idea_id'];
$inn_id = $_SESSION['inn_id'];

$con->query("INSERT INTO `myorder`(`ord_date`, `u_id`, `i_id`, `amount`, `inn_id`) VALUES ('$ord_date','$u_id','$i_id','$amount','$inn_id')");

$order_id = $con->insert_id;


$con->query("INSERT INTO `payment`(`user_id`, `order_id`,`amount`) VALUES ('$u_id','$order_id','$amount')");


$apiKey = "rzp_test_pLl681e9OrLq4X";
$profile_data = $con->query("select * from user where u_id='$u_id'");
$profile = $profile_data->fetch_object();


  
?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="http://localhost/oibp/Customer/success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo intval($_SESSION['price']) * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo $order_id;?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Online Innovators and Business Portal"
    data-description="Complete Business Solution"
    data-image="https://oibp1.000webhostapp.com/logo.PNG"
    data-prefill.name="<?php echo $profile->u_fname.' '.$profile->u_lname;?>"
    data-prefill.email="<?php echo $profile->email;?>"
    data-prefill.contact="<?php echo $profile->contact;?>"
    data-theme.color="#ff9902"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

